version: "3.8"

services:

  redis:
    container_name: redis
    image: redis:6.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    networks:
      - xiaofei-net
    # 根据自定义配置文件启动redis
    command: redis-server /etc/redis/redis.conf

  mysql:
    container_name: mysql
    image: mysql:8.0.19
    build:
      context: ./mysql
      dockerfile: dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: 'xiaofei-blog'
      MYSQL_USER: 'xiaofei'
      MYSQL_PASSWORD: 'xiaofei'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    networks:
      - xiaofei-net
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password #解决外部无法访问

  rabbitmq:
    container_name: rabbit
    image: rabbitmq:3.9-management
    restart: always
    hostname: my-rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - xiaofei-net

  nginx:
    container_name: nginx
    image: nginx:1.22
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/xiaofei/xiaofei-blog/nginx/html
      - ./nginx/cert:/xiaofei/xiaofei-blog/nginx/cert
    networks:
      - xiaofei-net

  # 一个一个的spring boot项目
  xiaofei-blog:
    container_name: xiaofei-blog
    image: xiaofei-blog:1.0
    restart: always
    build:
      context: ./xiaofei-blog
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    networks:
      - xiaofei-net
    depends_on:
      - redis
      - mysql
      - rabbitmq
    links:
      - redis
      - mysql
      - rabbitmq
networks:
  xiaofei-net:

#  docker run -d -p 3306:3306 -v /xiaofei/xiaofei-blog/mysql/conf:/etc/mysql/conf.d -v /xiaofei/xiaofei-blog/mysql/data:/var/lib/mysql --restart=always   -e MYSQL_ROOT_PASSWORD="root" --name mysql mysql:8.0.19
#  docker run -d --hostname my-rabbit --name rabbit --restart=always -p 15672:15672 -p 5672:5672  rabbitmq:3.9-management
#  docker run -d -p 6379:6379 --restart=always --name docker-redis redis
#  docker run --name nginx --restart=always -p 80:80 -d -v /xiaofei/xiaofei-blog/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /xiaofei/xiaofei-blog/xiaofei-blog-ui:/xiaofei/xiaofei-blog/xiaofei-blog-ui nginx

